// <auto-generated />
using System;
using CarSearch.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarSearch.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CarSearch.Api.Domain.Car", b =>
                {
                    b.Property<int>("StockNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AT_Position")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AskingPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AskingPriceWithoutCompulsoryRetailCustomerFee")
                        .HasColumnType("TEXT");

                    b.Property<int>("BHP")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BatteryCapacityKWH")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatteryRangeMiles")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BatteryUsableCapacityKWH")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarAgeBand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarDefaultImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Co2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateRegistered")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationSiteID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Doors")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EnginePower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnginePowerBand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngineSizeString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FinanceQuoteType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasImages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeadlineCaption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadlineDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadlineDescriptionNoYear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InsuranceGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InsuranceGroupLetter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InsuranceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InsuranceSecurityCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInPreparation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInStorage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsULEZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyFeaturesString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LowestMonthlyPayment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MOTExpiry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MPG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MPGBand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainThumbnailImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MakeFullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OptionalExstrasTotalValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreviousKeepers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriceLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrimaryTagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RRP_Autotrader")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegistrationPlateNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultImageSrcBlurred")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SaleText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Savings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Seats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiteID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusEnum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitterImageToUse")
                        .HasColumnType("TEXT");

                    b.Property<int>("WasPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WasPriceSaving")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebsitePrintURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StockNumber");

                    b.HasIndex("PrimaryTagId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarSearch.Api.Domain.CarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarStockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarStockNumber");

                    b.ToTable("CarImages");
                });

            modelBuilder.Entity("CarSearch.Api.Domain.ChargeTime", b =>
                {
                    b.Property<int>("ChargeTimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarStockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargerDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChargerSupplyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChargerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndBatteryPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartBatteryPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChargeTimeID");

                    b.HasIndex("CarStockNumber");

                    b.ToTable("ChargeTimes");
                });

            modelBuilder.Entity("CarSearch.Api.Domain.DepositQuote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarStockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepositAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuoteType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarStockNumber");

                    b.ToTable("DepositQuotes");
                });

            modelBuilder.Entity("CarSearch.Api.Domain.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BigUserIDRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BigUserIDVerified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarStockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateRemoved")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateVerified")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockFeatureEntryID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockFeatureTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarStockNumber");

                    b.HasIndex("StockFeatureTypeID");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("CarSearch.Api.Domain.FeatureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconHref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchSlug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowInSearchFilters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockFeatureTypeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FeatureTypes");
                });

            modelBuilder.Entity("CarSearch.Api.Domain.SliderImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarStockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClearImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarStockNumber");

                    b.ToTable("SliderImages");
                });

            modelBuilder.Entity("CarSearch.Api.Domain.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateRemoved")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoverDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisibleInWebsiteSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisibleOnWebsite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SashColorHtmlHexCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowsSashOnWebsite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebsiteClickHref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TagID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CarTags", b =>
                {
                    b.Property<int>("CarStockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CarStockNumber", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("CarTags");
                });

            modelBuilder.Entity("CarSearch.Api.Domain.Car", b =>
                {
                    b.HasOne("CarSearch.Api.Domain.Tag", "PrimaryTag")
                        .WithMany()
                        .HasForeignKey("PrimaryTagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrimaryTag");
                });

            modelBuilder.Entity("CarSearch.Api.Domain.CarImage", b =>
                {
                    b.HasOne("CarSearch.Api.Domain.Car", null)
                        .WithMany("WebsiteImageLinks")
                        .HasForeignKey("CarStockNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarSearch.Api.Domain.ChargeTime", b =>
                {
                    b.HasOne("CarSearch.Api.Domain.Car", null)
                        .WithMany("AutotraderTaxonomyChargeTimes")
                        .HasForeignKey("CarStockNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarSearch.Api.Domain.DepositQuote", b =>
                {
                    b.HasOne("CarSearch.Api.Domain.Car", null)
                        .WithMany("MonthlyPaymentWithDeposit")
                        .HasForeignKey("CarStockNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarSearch.Api.Domain.Feature", b =>
                {
                    b.HasOne("CarSearch.Api.Domain.Car", null)
                        .WithMany("Features")
                        .HasForeignKey("CarStockNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarSearch.Api.Domain.FeatureType", "FeatureType")
                        .WithMany()
                        .HasForeignKey("StockFeatureTypeID")
                        .HasPrincipalKey("StockFeatureTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureType");
                });

            modelBuilder.Entity("CarSearch.Api.Domain.SliderImage", b =>
                {
                    b.HasOne("CarSearch.Api.Domain.Car", null)
                        .WithMany("SliderImages")
                        .HasForeignKey("CarStockNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarTags", b =>
                {
                    b.HasOne("CarSearch.Api.Domain.Car", null)
                        .WithMany()
                        .HasForeignKey("CarStockNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarSearch.Api.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarSearch.Api.Domain.Car", b =>
                {
                    b.Navigation("AutotraderTaxonomyChargeTimes");

                    b.Navigation("Features");

                    b.Navigation("MonthlyPaymentWithDeposit");

                    b.Navigation("SliderImages");

                    b.Navigation("WebsiteImageLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
