CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017123035_InitialCreate') THEN
    CREATE TABLE "Features" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(250),
        CONSTRAINT "PK_Features" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017123035_InitialCreate') THEN
    CREATE TABLE "Makes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        CONSTRAINT "PK_Makes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017123035_InitialCreate') THEN
    CREATE TABLE "Models" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "MakeId" integer NOT NULL,
        CONSTRAINT "PK_Models" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Models_Makes_MakeId" FOREIGN KEY ("MakeId") REFERENCES "Makes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017123035_InitialCreate') THEN
    CREATE TABLE "Generations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "StartYear" smallint,
        "EndYear" smallint,
        "ModelId" integer NOT NULL,
        CONSTRAINT "PK_Generations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Generations_Models_ModelId" FOREIGN KEY ("ModelId") REFERENCES "Models" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017123035_InitialCreate') THEN
    CREATE TABLE "Variants" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Engine" character varying(100),
        "Transmission" character varying(50),
        "FuelType" character varying(50),
        "GenerationId" integer NOT NULL,
        CONSTRAINT "PK_Variants" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Variants_Generations_GenerationId" FOREIGN KEY ("GenerationId") REFERENCES "Generations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017123035_InitialCreate') THEN
    CREATE TABLE "VariantFeatures" (
        "VariantId" integer NOT NULL,
        "FeatureId" integer NOT NULL,
        "IsStandard" boolean NOT NULL DEFAULT TRUE,
        "AddedDate" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_VariantFeatures" PRIMARY KEY ("VariantId", "FeatureId"),
        CONSTRAINT "FK_VariantFeatures_Features_FeatureId" FOREIGN KEY ("FeatureId") REFERENCES "Features" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_VariantFeatures_Variants_VariantId" FOREIGN KEY ("VariantId") REFERENCES "Variants" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017123035_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Features_Name" ON "Features" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017123035_InitialCreate') THEN
    CREATE INDEX "IX_Generations_ModelId" ON "Generations" ("ModelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017123035_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Makes_Name" ON "Makes" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017123035_InitialCreate') THEN
    CREATE INDEX "IX_Models_MakeId" ON "Models" ("MakeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017123035_InitialCreate') THEN
    CREATE INDEX "IX_VariantFeatures_FeatureId" ON "VariantFeatures" ("FeatureId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017123035_InitialCreate') THEN
    CREATE INDEX "IX_Variants_GenerationId" ON "Variants" ("GenerationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251017123035_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251017123035_InitialCreate', '9.0.4');
    END IF;
END $EF$;
COMMIT;

